CREATE DATABASE IF NOT EXISTS chat;
USE chat;
CREATE TABLE IF NOT EXISTS message
(
    `id`       INT(11)      NOT NULL AUTO_INCREMENT,
    `fullName` VARCHAR(255) NOT NULL,
    `message`    VARCHAR(15000) NOT NULL,
    PRIMARY KEY (`id`)
) ENGINE = InnoDB;
